services:
  # --- Backend (Node/Express) ---
  - type: web
    name: cv-backend
    env: node
    plan: free
    branch: main            # o master, la que uses
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start  # usa tu "start" (node src/app.js)
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      # Carg치 estas desde el panel (no commitees secretos):
      # - key: MONGODB_URI
      #   sync: false
      # - key: JWT_SECRET
      #   sync: false

  # --- Frontend (React/Vite/CRA) como sitio est치tico ---
  - type: static_site
    name: cv-frontend
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist   # Vite => "dist"; si us치s CRA, cambi치 a "build"
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      # Si tu frontend necesita apuntar al backend:
      # - key: VITE_API_URL        # o REACT_APP_API_URL (CRA)
      #   value: https://cv-backend.onrender.com
